##The website title
name: Wolfgang's Page
##Markdown processor
markdown: kramdown
##syntax highlighter. change it to pygments
highlighter: pygments

##define base_url for valid usage in sitemap.xml and robots.txt
base_url: https://wolfgangwiesinger.github.io/
sass:
  sass_dir: _sass
  style: :compressed
paginate: 5
paginate_path: "page:num"
##The website description (to be used in meta tags)
description: This Homepage is an assignment project for an university course.
##Some frequently used keywords on your website
keywords: 

##define this for disqus comment support
#disqus: forumname

##set this to enable google analytics
#ga_id: analyticsID
#ga_domain: analyticsDomain

##Some commonly used links
links:
  facebook: wolfgang.wiesinger
  twitter: wol_89
  email: username@gmail.com
  github: WolfgangWiesinger

##put desired image in img/ directory and set the value accordingly. If not defined, a placeholder image will be used.
#about_image: placeholder.jpg
##comment this if you want full width posts with no sidebar
sidebar: on
